site_name: Pyr0-Piezo
site_description: Documentation for the Pyr0-Piezo Z-probe sensor
site_author: Alan "pyr0ball" Weinstock
repo_url: https://github.com/pyr0ball/pyr0piezo/

theme:
  name: 'material'
  logo: 'assets/images/Pyr0ball-logo.png'
  favicon: 'assets/images/Pyr0ball-logo.png'
  custom_dir: 'mkdocs-theme-overrides'
  #palette:
  #  primary: 'orange'
  #  accent: 'light orange'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

markdown_extensions:
  #http://pythonhosted.org/Markdown/extensions/admonition.html
  - admonition:
  - mdx_truly_sane_lists:
  - toc: 
      permalink: True

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - FAQ: 'faq.md'
  - Installation:
    - Start Here: 'installation.md'
    - Wiring Diagrams:
      - EasyPiezi:
        - EasyPiezi Wiring Harness: 'tutorials/wiring/easy-piezi/harness-pinout.md'
        - Monoprice Delta Mini: 'tutorials/wiring/easy-piezi/monoprice-delta-mini.md'
        # - Creality 1284P: 'tutorials/wiring/easy-piezi/creality-1284.md'
        # - Duet Wifi: 'tutorials/wiring/easy-piezi/duet-wifi.md'
        # - MKS Family:
        #   - MKS Base 1.4: 'tutorials/wiring/easy-piezi/mks-base.md'
        #   - MKS Gen L: 'tutorials/wiring/easy-piezi/mks-gen-l.md'
        #   - MKS SBase: 'tutorials/wiring/easy-piezi/mks-sbase.md'
        - RAMPS 1.4: 'tutorials/wiring/easy-piezi/ramps-1.4.md'
        - Power from 3.3v/5V: 'tutorials/wiring/easy-piezi/unregulated-operation.md'
      - pP-FFC:
        - Creality 1284P: 'tutorials/wiring/pp-ffc/creality-1284.md'
        - Duet Wifi: 'tutorials/wiring/pp-ffc/duet-wifi.md'
        - MKS Family:
          - MKS Base 1.4: 'tutorials/wiring/pp-ffc/mks-base.md'
          - MKS Gen L: 'tutorials/wiring/pp-ffc/mks-gen-l.md'
          - MKS SBase: 'tutorials/wiring/pp-ffc/mks-sbase.md'
        - RAMPS 1.4: 'tutorials/wiring/pp-ffc/ramps-1.4.md'
    - Printer Specific:
      - Core XY:
        - Hypercube Evo (On Head): 'mounts/core-xy/hevo-on-head.md'
        - Railcore II (Under-Bed): 'mounts/core-xy/railcore-ii.md'
      - Creality Family:
        - CR-10 Family: 'mounts/creality/creality-original-head.md'
        - Ender 3 Family: 'mounts/creality/creality-original-head.md'
      - Delta:
        - On Head: 'mounts/delta/delta-head.md'
        - Under Bed: 'mounts/delta/delta-under-bed.md'
      - Deltesian: 'mounts/deltesian/deltesian.md'
      - Mendel:
        - On Head: 'mounts/mendel/mendel-on-head.md'
        - Gantry Mount: 'mounts/mendel/mendel-gantry-mount.md'
      - Prusa Mendel:
        - Prusa i3 on Head: 'mounts/prusa-mendel/i3-on-head.md'
        - HICTOP i3: 'mounts/prusa-mendel/hictop-i3.md'
      - Quadrap:
        - Makerbot Original Under Bed: 'mounts/quadrap/makerbot-under-bed.md'
        - Ultimaker Under Bed: 'mounts/quadrap/um-under-bed.md'
  - Configuration:
    - Update Sensor:
      - Sensor UART Wiring: 'schematics/other/uart-programmer-wiring.md'
      - Firmware Update: 'tutorials/firmware-update/beta-unit-firmware-update.md'
    - Pyr0-Piezo Config: 'config.md'
    - Settings Explaination: 'tutorials/config/pyr0piezo-parameters/pyr0piezo-parameters.md'
    - Printer Firmware Config:
      - Marlin: 'tutorials/config/printer-firmware/marlin/marlin-config.md'
      - Klipper: 'tutorials/config/printer-firmware/klipper/klipper-config.md'
      - RepRapFirmware v2: 'tutorials/config/printer-firmware/rrf-v2/rrf-v2-config.md'
      - RepRapFirmware v3: 'tutorials/config/printer-firmware/rrf-v3/rrf-v3-config.md'
  - Extras:
    - PT100 RTD Thermal Sensor: 'tutorials/extras/pt100.md'
  - Resources:
    - 3D Models:
      - Fusion 360 Sources: 'models/all-f360-sources.md'
    - Sensor Datasheet:
      - I2C Integration: 'tutorials/config/pyr0piezo-i2c/pyr0piezo-i2c.md'
    - Schematics:
      - EasyPiezi: 'schematics/easypiezi/easypiezi-schematics.md'
      - FFC Direct Extruder: 'schematics/ffc-direct-extruder/ffc-direct-extruder-schematics.md'
      - FFC Direct Breakout: 'schematics/ffc-direct-breakout/ffc-direct-breakout-schematics.md'
    - Drawings:
      - Board Layouts:
        - EasyPiezi: 'drawings/layouts/easypiezi/easypiezi-layouts.md'
        - FFC Direct Extruder:
          - FFC Direct Extruder 1.1.0 Top: 'drawings/layouts/ffc-direct-extruder/Pyr0-Piezo_FFC_Extruder_Boardv1.1.0_Components_Front.pdf'
        #- FFC Direct Breakout:
      - Connector Pinouts:
        - EasyPiezi: 'drawings/pinouts/easypiezi/easypiezi-pinouts.md'
        - FFC Direct Extruder: 'drawings/pinouts/ffc-direct-extruder/ffc-direct-extruder-pinouts.md'
        - FFC Direct Breakout: 'drawings/pinouts/ffc-direct-breakouts/ffc-direct-breakout-pinouts.md'
      - Test Pads Layout: 'drawings/pyro-piezo-test-pads.md'
    - Changelog:
      - Version List: 'changelog.md'
      - Logs:
        - 'v2.2.1-v2.3.0': 'changelogs/changelog_2020-05-10_v2.2.1_v2.3.0.md'
        - 'v2.2.0-v2.2.1': 'changelogs/changelog_2020-01-16_v2.2.0_v2.2.1.md'
        - 'v2.1.5-v2.1.6': 'changelogs/changelog_2019-12-28_v2.1.5_v2.1.6.md'
        - 'v2.1.4-v2.1.5': 'changelogs/changelog_2019-10-30_v2.1.4_v2.1.5.md'
        - 'v2.1.3-v2.1.4': 'changelogs/changelog_2019-10-09_v2.1.3_v2.1.4.md'
        - 'v2.1.2-v2.1.3': 'changelogs/changelog_2019-09-25_v2.1.2_v2.1.3.md'
        - 'v2.1.1-v2.1.2': 'changelogs/changelog_2019-08-15_v2.1.1_v2.1.2.md'
        - 'v2.0.2-v2.1.1': 'changelogs/changelog_2019-08-15_v2.0.2_v2.1.1.md'
        - 'v2.0.1_hw-v2.0.2': 'changelogs/changelog_2019-08-15_v2.0.1_hw_v2.0.2.md'
        - 'v2.0.1-v2.0.1_hw': 'changelogs/changelog_2019-08-15_v2.0.1_v2.0.1_hw.md'
        - 'v2.0.0-v2.0.1': 'changelogs/changelog_2019-08-15_v2.0.0_v2.0.1.md'
        - '76b4ba6-v2.0.0': 'changelogs/changelog_2019-08-15_76b4ba6_v2.0.0.md'
        - 'cfa0abc-76b4ba6': 'changelogs/changelog_2019-08-15_cfa0abc_76b4ba6.md'
        - '551fcb7-cfa0abc': 'changelogs/changelog_2019-08-15_551fcb7_cfa0abc.md'

  - Main Site: 'https://pyroballpcbs.com'

google_analytics: ['UA-135668867-1', 'pyroballpcbs.com']
